### PR TITLE
First round of conversion to DocBook 5

### PR DESCRIPTION
**Pull request by tomschr**
This PR contains the first draft of the transition to DocBook 5. The guides validate against DocBook 5 (not Geekodoc!).

The procedure of the transition (also available as a [conversion script](https://github.com/sknorr/daps-migrate-tools/blob/master/migrate2docbook5.sh)):

1. Create a temporary xml folder.
1. Protect the entities with `lib/entities.preserve.sed`.
1. Copy `*.ent` files in temporary xml directory.
1. Convert to DocBook 5 with the styleseheet `daps-xslt/migrate/suse-upgrade.xsl`.
1. Restore protected entities with `lib/entities.recover.sed`.

I've started with English first as it's simpler and to fine-tune the process. This allows us to roll out any changes to the other languages. Let me know if you discover something odd. :wink:

### CODE REVIEW

**Comment by ghost** [comment]
* Looks good in general, at first glance

* Validating with Geekodoc finds at least one type of conversion issue that should be fixed -- `ay_bigfile.xml:11259:44: error: attribute "linkend" not allowed here`: we create `<link linkend="CreateProfile-General">General Options</link>` instead of `xref linkend=...` -- I know for a fact that our current stylesheets do not properly support using `link linkend=`. To make this work properly for us, please fix those. (This is a stylesheet bug but it'd still be easier to fix this here now.)

* I don't like the fact that your script changes the formatting of \<info/\> elements so much. If there is a simple way from within your script to include line breaks into those, that would be great, both for reviewing now and for possible later edits. (You could also try `daps -d ... xmlformat` on everything but that might just bring too many change, completely destroying git blame-ability.)
* For the translations, resetting all type-changed files (symlink->regular file) might be helpful: `git checkout -- $(git status | sed -n 's/[ \t]*typechange:[ \t]*// p')` [needs to be run before committing!]

**Comment by tomschr** [comment]
Thanks for the review, much appreciated! :+1:  I'll try to address your suggestions. 

> Validating with Geekodoc finds at least conversion issue [...] (This is a stylesheet bug but it'd still be easier to fix this here now.)

Right, I'll look into this and try to fix it.

> I don't like the fact that your script changes the formatting of <info/> elements so much.

Yes, that's the `suse-upgrade.xsl` stylesheet which is based on Norman Walsh's `db4-upgrade.xsl`.

Regarding the formatting: would it be an option to call `daps xmlformat` on the  `maintenance/SLE11SP4` **and** the feature branch? That should keep the formatting correct. However, it can also introduce some formatting issues...

At least it has the benefit that the stylesheet does not need to be adjusted.

**Comment by ghost** [comment]
> Regarding the formatting: would it be an option to call daps xmlformat on the maintenance/SLE11SP4 and the feature branch? That should keep the formatting correct. However, it can also introduce some formatting issues...

I think you misunderstood me. Definitely only do it once and here on this branch. I was mostly thinking aloud whether it made sense to do it at all.
However, we did not import any history into this repo anyway, so just go for the reformatting--this repo can't be used for code-archeological purposes either way.

**Comment by tomschr** [comment]
> I think you misunderstood me. Definitely only do it once and here on this branch.

Allright, I'll do the xmlformat here on this feature branch only. Thanks for clarifying!

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
